# Generated by Django 2.2.12 on 2020-04-12 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cerapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='author',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='post',
            name='text',
        ),
        migrations.RemoveField(
            model_name='post',
            name='title',
        ),
    ]
